enable:
  swagger2: true

spring:
  application:
    name: blog-web
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mariadb://192.168.1.88:3306/MyBlog?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
